# --- QMIX specific parameters ---
experiment: "updet_visualization"

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

# runner: "parallel" # "parallel"
# batch_size_run: 8
# buffer_size: 5000
# batch_size: 128

runner: "episode" # "parallel" episode
batch_size_run: 1
buffer_size: 5000
batch_size: 1

# update the target network every {} episodes
target_update_interval: 200

# controller
mac: "hpn_mac"

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

hgap_hyper_dim: 128

name: "qmix"
